// Barrel file: re-exports all supabase data operations from specialized modules
// This maintains backward compatibility with 256+ existing imports while internally
// organizing code into three focused domains: studios, bookings, and members.

// ─── Studios & Core Infrastructure ──────────────────────────────────────────
export {
  setCurrentStudioId,
  getCurrentStudioId,
  resolveStudioId,
  setDbErrorListener,
  fetchCriticalStudioData,
  fetchDeferredStudioData,
  fetchAllStudioData,
  fetchPublicStudioData,
  mapMensajeEquipo,
  mapCanalEquipo,
  mapServicioCita,
  mapDisponibilidadCita,
  dbSetTerminalReader,
  dbCreateStudio,
  resolveStudioIdBySlug,
  dbUpdateStudioAvatar,
  dbUpdateStudio,
  dbSetStripeAccountId,
  dbSetGoogleCalendarEmail,
  dbGetGoogleCalendarCredenciales,
  dbSaveGoogleCalendarCredenciales,
  dbDeleteGoogleCalendarCredenciales,
  dbSetGmailEmail,
  dbGetGmailCredenciales,
  dbSaveGmailCredenciales,
  dbDeleteGmailCredenciales,
  dbSetZoomEmail,
  dbGetZoomCredenciales,
  dbSaveZoomCredenciales,
  dbDeleteZoomCredenciales,
  dbGetIntegracionConfig,
  generateUniqueSlug,
  fetchMisEstudios,
  cambiarSedeActiva,
  dbInsertInstructor,
  dbUpdateInstructor,
  dbDeleteInstructor,
  dbClaimInstructorAccount,
  generarRecordatoriosRevision,
  barrerNoShows,
  enviarRecordatoriosClasesProximas,
  type PublicStudioData,
  type GoogleCalendarCredenciales,
  type GmailCredenciales,
  type ZoomCredenciales,
  type SedeSeleccionable,
} from './supabase/studios';

// ─── Public Bookings & Reservations ─────────────────────────────────────────
export {
  crearReservaPublica,
  cancelarReservaPublica,
  ejecutarCancelacionReserva,
  fetchCatalogoCitasPublico,
  fetchHuecosCitaPublico,
  crearCitaPublica,
  cancelarCitaPublica,
  resolverSociaAutenticada,
  socioAutenticado,
  registrarSociaPublica,
  actualizarSociaPublica,
  guardarPreferenciasPublica,
  canjearRecompensaPublica,
  validarKioskToken,
  checkinPublico,
  dbInsertSesion,
  dbInsertSesionesBatch,
  dbUpdateSesionesBatch,
  dbUpdateSesion,
  dbDeleteSesion,
  dbInsertReserva,
  dbReservarPlaza,
  dbCancelarReservaPlaza,
  dbUpdateReserva,
  dbInsertRecibo,
  dbUpdateRecibo,
  dbUpdateRecibosBatch,
  dbDeleteRecibo,
  dbInsertCita,
  dbUpdateCita,
  dbInsertVentaPOS,
  dbInsertProductoPOS,
  dbUpdateProductoPOS,
  dbDeleteProductoPOS,
  dbInsertSuscripcion,
  dbUpdateSuscripcion,
  dbMarcarNotificacionLeida,
  dbMarcarNotificacionesLeidas,
  dbUpsertPreferenciasSocio,
  dbInsertServicioCita,
  dbUpdateServicioCita,
  dbDeleteServicioCita,
  dbReplaceDisponibilidadCitas,
} from './supabase/bookings';

// ─── Members & Team Management ───────────────────────────────────────────────
export {
  dbInsertSocio,
  dbUpdateSocio,
  dbDeleteSocio,
  dbFetchCamposPersonalizados,
  dbInsertCampoPersonalizado,
  dbUpdateCampoPersonalizado,
  dbDeleteCampoPersonalizado,
  dbFetchDependencySnapshots,
  dbFetchPlantillasEmail,
  dbUpsertPlantillaEmail,
  dbListComentariosComunidad,
  dbAddComentarioComunidad,
  dbInsertPlanTarifa,
  dbUpdatePlanTarifa,
  dbDeletePlanTarifa,
  dbInsertRewardRule,
  dbUpdateRewardRule,
  dbClaimRecompensaUnica,
  dbInsertRewardHistory,
  dbInsertCreditTransaction,
  dbAjustarCreditos,
  dbAjustarStock,
  dbConsumirSesionBono,
  dbUpsertMemberCredits,
  dbInsertRewardCatalogItem,
  dbUpdateRewardCatalogItem,
  dbDeleteRewardCatalogItem,
  dbInsertRewardRedemption,
  dbUpdateRewardRedemption,
  dbInsertAchievementDefinition,
  dbUpdateAchievementDefinition,
  dbUpsertAchievementProgress,
  dbInsertAchievementHistory,
  dbInsertLevelDefinition,
  dbUpdateLevelDefinition,
  dbDeleteLevelDefinition,
  dbInsertChallengeDefinition,
  dbUpdateChallengeDefinition,
  dbDeleteChallengeDefinition,
  dbUpsertChallengeProgress,
  dbInsertChallengeHistory,
  dbInsertDashboardChart,
  dbDeleteDashboardChart,
  dbInsertAutomationLog,
  dbUpsertAutomationLog,
  dbUpdateAutomationLog,
  dbInsertAutomationRule,
  dbUpdateAutomationRule,
  dbInsertNotaProgreso,
  dbInsertNotaInterna,
  dbDeleteNotaInterna,
  dbInsertCodigoDescuento,
  dbUpdateCodigoDescuento,
  dbConsumirCodigoDescuento,
  dbDeleteCodigoDescuento,
  dbInsertCondicion,
  dbUpdateCondicion,
  dbDeleteCondicion,
  dbInsertRespuestaSesion,
  dbUpdateRespuestaSesion,
  dbInsertRewardAction,
  dbInsertCampana,
  dbUpdateCampana,
  dbDeleteCampana,
  dbInsertAutomatizacion,
  dbUpdateAutomatizacion,
  dbDeleteAutomatizacion,
  dbInsertVideoOnDemand,
  dbUpdateVideoOnDemand,
  dbDeleteVideoOnDemand,
  dbInsertPostComunidad,
  dbUpdatePostComunidad,
  dbToggleLikePost,
  dbMisLikesComunidad,
  dbDeletePostComunidad,
  dbUpsertIntegracion,
  dbInsertActividadReciente,
  dbListMensajesEquipo,
  dbListCanalesEquipo,
  dbCreateCanalEquipo,
  dbInsertMensajeEquipo,
  dbInsertTipoClase,
  dbUpdateTipoClase,
  dbDeleteTipoClase,
  dbInsertSoporteSolicitud,
} from './supabase/members';
