-- PAY-5: detector de doble cobro — SUPERSEDIDA.
--
-- Esta migración figura como aplicada en el registro de producción pero NUNCA
-- creó nada: ni la tabla `dobles_cobros_detectados` ni `detectar_dobles_cobros`
-- existían allí (verificado el 2026-09-21 y el 2026-09-25). Tenía además dos
-- defectos (`studio_id uuid` cuando `studios.id` es text, y una función
-- SECURITY DEFINER sin decisión sobre `anon`).
--
-- El detector de verdad —tabla, función y cron— vive ahora en
-- 20260925011839_pay5b_detector_dobles_cobros_vivo.sql. El contenido original se
-- ha retirado para que reconstruir la base desde el repo no cree dos veces la
-- misma tabla ni una función con la semántica equivocada (contaba TODOS los
-- PaymentIntent de un recibo, también los rechazados).
select 1;
