import type { Articulo } from './tipos.ts';

const NOTA_MUESTRA = 'Muestra de 32 estudios con precios publicados en su web, consultada el 25-sep-2026; sin clases de prueba ni promociones. Metodología y fuentes, al final.';

const articulo: Articulo = {
  slug: 'precio-clase-de-pilates',
  titulo: 'Precio de una clase de pilates en 2026: lo que cobran 32 estudios en España',
  tituloSeo: 'Precio de una clase de pilates en 2026: 32 estudios',
  descripcion: 'Clase suelta de reformer: 25 € de mediana; de suelo, 16 €; privada, 53,50 €. Precios reales de 32 estudios de 8 ciudades y cómo fijar el tuyo.',
  resumen: 'Lo que cobran 32 estudios de Madrid, Barcelona, Valencia, Sevilla, Bilbao, Málaga, Zaragoza y Alicante: clase suelta, cuotas y bonos de reformer, suelo y privada, con medianas y rangos.',
  categoria: 'rentabilidad',
  seccion: 'Rentabilidad',
  publicado: '2026-09-25',
  consultaPrincipal: 'precio de una clase de pilates',
  consultas: [
    'precio clase pilates reformer',
    'precio medio clase de pilates',
    'precio clase particular pilates',
    'precio clase pilates suelo',
    'cuánto cobrar por una clase de pilates',
  ],
  respuesta: 'Según las tarifas que publican 32 estudios de 8 ciudades españolas (consultadas el 25 de septiembre de 2026), el precio de una clase de pilates depende sobre todo del formato: la clase suelta de reformer en grupo va de 17 a 35 € (mediana: 25 €), la de suelo, de 12 a 25 € (mediana: 16 €), y la privada, de 40 a 75 € (mediana: 53,50 €). Con cuota de una clase semanal, la sesión de reformer baja a 18,75 €.',
  entradilla: 'Casi todo lo que circula sobre el precio de una clase de pilates son horquillas sin fuente. Aquí tienes lo que cobran de verdad 32 estudios que publican sus tarifas: clase suelta, cuotas y bonos de reformer, suelo y privada, qué explica las diferencias y cómo fijar tu precio.',
  secciones: [
    {
      id: 'precio-de-una-clase-de-pilates-en-2026',
      titulo: 'Precio medio de una clase de pilates en 2026: la tabla',
      bloques: [
        { t: 'p', texto: 'Hemos abierto la página de tarifas de 32 estudios de Madrid, Barcelona, Valencia, Sevilla, Bilbao, Málaga, Zaragoza y Alicante y hemos anotado lo que cobran por cada formato. Primero, la **clase suelta**: la que paga quien viene un día sin compromiso.' },
        {
          t: 'tabla',
          cabecera: ['Formato', 'Estudios con dato', 'Mínimo', 'Mediana', 'Máximo'],
          filas: [
            ['Reformer o máquinas, en grupo', '18', '17 €', '25 €', '35 €'],
            ['Suelo (mat), en grupo', '7', '12 €', '16 €', '25 €'],
            ['Privada (una alumna)', '16', '40 €', '53,50 €', '75 €'],
          ],
          nota: `Precio de la clase suelta. ${NOTA_MUESTRA}`,
        },
        { t: 'p', texto: 'La suelta es la opción más cara por sesión. Casi todos los estudios empujan hacia la cuota mensual —31 de los 32 publican alguna— y ahí el precio por sesión baja. Así queda con cuota o con bono:' },
        {
          t: 'tabla',
          cabecera: ['Formato', 'Cuota de 1 clase a la semana', 'Por sesión, 1 clase a la semana', 'Por sesión, 2 clases a la semana', 'Por sesión, bono de 10'],
          filas: [
            ['Reformer o máquinas, en grupo', '75 €/mes (60–133) · 23 estudios', '18,75 € (15–33,25)', '16,25 € (13,13–25) · 23 estudios', '21,10 € (17,90–28) · 10 estudios'],
            ['Suelo (mat), en grupo', '55 €/mes (35–75) · 8 estudios', '13,75 € (8,75–18,75)', '10,63 € (6,25–17,50) · 7 estudios', '12,50 y 13,50 € · 2 estudios'],
            ['Privada (una alumna)', '160 €/mes (145–180) · 5 estudios', '40 € (36,25–45)', '35,94 € (34,38–40,63) · 4 estudios', '44,13 € (30–55) · 13 estudios, bonos de 8 a 10'],
          ],
          nota: 'Mediana y, entre paréntesis, mínimo y máximo. Cuota de N clases a la semana = 4N sesiones al mes, la cuenta que enseñan en su web Horta Pilates (80 €/mes = 20 €/clase) y Temple Pilates (99 €/mes = 24,75 €/clase). Misma muestra de 32 estudios, 25-sep-2026.',
        },
        { t: 'p', texto: 'Dos lecturas rápidas. En los 15 estudios que publican a la vez clase suelta y cuota de reformer, la cuota de una clase a la semana sale una mediana del **20 % más barata por sesión** que la suelta. Y pasar de una a dos clases a la semana rebaja la sesión otro **16 %** de mediana (entre el 4,5 % y el 31 %, según el estudio).' },
      ],
    },
    {
      id: 'precio-clase-pilates-reformer',
      titulo: 'Precio de una clase de pilates reformer',
      bloques: [
        { t: 'p', texto: 'El reformer —junto con las demás máquinas: torre, cadillac, silla— es el formato con más oferta: 26 de los 32 estudios lo venden en grupo. La clase suelta va de 17 a 35 € y dos de cada tres estudios cobran entre 25 y 30 €. En cuota mensual, una clase a la semana cuesta **75 € de mediana** y dos clases, **130 €** (de 105 a 200 €).' },
        { t: 'p', texto: 'El tamaño del grupo cambia mucho de un estudio a otro: los hay con un máximo de 4 personas por clase y uno con hasta 12 reformers por sesión. Y el precio no sigue una regla fija con el tamaño: solo entre los estudios con grupos de 4 o 5 personas hay cuotas de 70 y de 133 € al mes por una clase semanal.' },
        { t: 'p', texto: 'Los bonos de 10 sesiones de reformer cuestan entre 179 y 280 € (mediana: 211 €), es decir, entre 17,90 y 28 € la sesión. Comparado con la clase suelta del mismo estudio, el bono de 10 ahorra entre un 7 % y un 33 % (mediana: 21 %). Si estás montando los tuyos, en [cómo diseñar bonos de pilates](/recursos/bonos-de-pilates) tienes la escalera completa y las caducidades que usan estos estudios.' },
        { t: 'p', texto: 'Algunos estudios venden además tarifa ilimitada de reformer: en la muestra, 185, 195 y 250 € al mes.' },
      ],
    },
    {
      id: 'precio-clase-pilates-suelo',
      titulo: 'Precio de una clase de pilates suelo (mat)',
      bloques: [
        { t: 'p', texto: 'El suelo es bastante más barato. La clase suelta va de 12 a 25 € (mediana: 16 €) y la cuota de una clase a la semana, de 35 a 75 € al mes (mediana: 55 €, es decir, 13,75 € por sesión). Con dos clases a la semana, la sesión baja a 10,63 € de mediana.' },
        { t: 'p', texto: 'Dentro de un mismo estudio la comparación es más limpia. En los seis que permiten comparar los dos formatos con la misma tarifa, la máquina siempre cuesta más: entre **1,27 y 2,2 veces** el suelo, con una mediana de 1,6 en la cuota de una clase semanal. El aforo del reformer lo fija el número de máquinas, y cada una es inversión; en suelo, otra esterilla cabe casi gratis. Lo desarrollamos en [reformer vs. mat: cómo poner precio a cada clase](/recursos/precios-reformer-mat).' },
      ],
    },
    {
      id: 'precio-clase-particular-pilates',
      titulo: 'Precio de una clase particular de pilates',
      bloques: [
        { t: 'p', texto: 'La clase privada (una alumna con su instructora, casi siempre con máquinas) cuesta entre 40 y 75 € suelta, con una mediana de **53,50 €**. Con bono de 8 a 10 sesiones baja a entre 30 y 55 € (mediana: 44,13 €), un 18 % menos que la suelta del mismo estudio. El bono de 10 privadas cuesta entre 300 y 550 € (mediana: 456 €), y quien la vende en cuota cobra de 145 a 180 € al mes por una sesión semanal.' },
        { t: 'p', texto: 'En los ocho estudios que venden privada y grupo de reformer, la privada cuesta unas dos veces la clase de grupo (entre 1,6 y 2,5 veces). Entre medias están las clases de dos o tres personas: el dúo, por ejemplo, cuesta 40 € por persona en Area Pilates y 45 € en Temple Pilates y en Beyoga; el trío, 40 € por persona en Temple.' },
        { t: 'p', texto: 'Un detalle que se repite: 10 de los 32 estudios venden una **primera sesión privada de valoración, iniciación o prueba**. Suelta cuesta entre 35 y 50 €, y dos estudios la empaquetan con otras clases (100 y 120 €). Al menos uno la declara obligatoria para empezar. Sirve para colocar a la alumna en su nivel y para cobrar el tiempo extra que exige alguien nuevo en máquinas.' },
      ],
    },
    {
      id: 'precio-por-ciudad',
      titulo: '¿Es más caro el pilates en Madrid o en Barcelona? El precio por ciudad',
      bloques: [
        {
          t: 'tabla',
          cabecera: ['Ciudad', 'Estudios con cuota', 'Mediana', 'Valores o rango'],
          filas: [
            ['Madrid', '8', '79,50 €/mes', '70–100 €'],
            ['Barcelona', '4', '84,50 €/mes', '69–133 €'],
            ['Sevilla', '3', '80 €/mes', '75–110 €'],
            ['Valencia', '2', '—', '65 y 74 €'],
            ['Málaga', '2', '—', '60 y 71 €'],
            ['Bilbao', '2', '—', '75 y 92 €'],
            ['Zaragoza y Alicante', '2', '—', '70 y 75 €'],
            ['Todas menos Madrid y Barcelona', '11', '75 €/mes', '60–110 €'],
          ],
          nota: 'Cuota mensual de reformer o máquinas en grupo con una clase a la semana (o 4 clases al mes). Con tan pocos estudios por ciudad, las medianas son orientativas; con dos, se dan los valores. Misma muestra de 32 estudios, 25-sep-2026.',
        },
        { t: 'p', texto: 'Madrid y Barcelona salen algo por encima (79,50 y 84,50 € frente a 75 €), pero la diferencia entre ciudades es menor que dentro de una misma ciudad: en Barcelona hay cuotas de 69 y de 133 € por una clase semanal. Pesan más el tamaño del grupo y el tipo de estudio que la ciudad: compárate con los estudios de tu zona y tu formato, no con una media nacional.' },
      ],
    },
    {
      id: 'que-explica-las-diferencias',
      titulo: 'Qué explica que una sesión cueste 15 € en un estudio y 33 € en otro',
      bloques: [
        {
          t: 'lista',
          items: [
            '**El formato.** La máquina cuesta entre 1,27 y 2,2 veces el suelo en el mismo estudio.',
            '**El tamaño del grupo.** De 4 a 12 personas por clase. Un grupo pequeño da más atención y menos ingresos por clase: si es tu caso, el precio tiene que compensarlo.',
            '**El compromiso.** Frente a la suelta, el bono de 10 ahorra una mediana del 21 % y la cuota de una clase semanal, un 20 %; la de dos clases rebaja otro 16 %.',
            '**La franja.** Estación Pilates (Madrid) cobra 78 € en vez de 85 € al mes por una clase semanal de mañana: la lógica de las [clases valle](/recursos/ocupacion-clases-valle).',
            '**La entrada.** Cuatro estudios publican una matrícula (de 10 a 50 €), otros la anuncian como inexistente o la regalan con permanencia, y diez venden una sesión privada de valoración.',
            '**El tipo de estudio.** En Barcelona, la cuota de una clase semanal va de 69 € en una cadena de reformer a 133 € en un estudio con grupos de 4.',
          ],
        },
      ],
    },
    {
      id: 'cuanto-cobrar-por-una-clase-de-pilates',
      titulo: 'Cuánto cobrar por una clase de pilates: cómo fijar tu precio',
      bloques: [
        { t: 'p', texto: 'Estos datos te dicen dónde está el mercado, no cuál es tu precio. Para fijarlo, sigue este orden:' },
        {
          t: 'pasos',
          items: [
            { titulo: 'Calcula tu suelo', texto: 'Suma lo que te cuesta cada clase (instructora, local, máquinas, comisiones) y divídelo entre las plazas que llenas de verdad: por debajo, pierdes dinero aunque la clase esté llena. Paso a paso en [¿es rentable un estudio de pilates?](/recursos/rentabilidad-estudio-de-pilates).' },
            { titulo: 'Mira tu zona y tu formato', texto: 'Abre las tarifas de cinco a diez estudios cercanos con tu formato y grupos parecidos. La mediana nacional solo te dice si estás muy lejos del mercado.' },
            { titulo: 'Elige tu producto estrella', texto: 'Casi siempre, una cuota mensual: 31 de los 32 estudios publican alguna. Decide si empujas la de una o la de dos clases semanales y construye el resto alrededor.' },
            { titulo: 'Escalona el precio por sesión', texto: 'Suelta arriba, bonos en medio y la cuota con más clases abajo, con descuentos parecidos a los de la muestra. Detalles en [bonos de pilates: cómo diseñarlos](/recursos/bonos-de-pilates).' },
            { titulo: 'Separa máquinas y suelo', texto: 'Si das los dos, que se note: la máquina cuesta 1,6 veces el suelo de mediana.' },
            { titulo: 'Protege el precio', texto: 'Un buen precio con huecos vacíos rinde menos que uno algo más bajo con la clase llena. Ventana de cancelación y lista de espera: mira [cómo reducir las cancelaciones de última hora](/recursos/reducir-cancelaciones-ultima-hora).' },
            { titulo: 'Publícalo bien', texto: 'Precio por sesión al lado de cada cuota y precio final: la ley de consumidores obliga a informar del precio total, con impuestos, antes de contratar. Si tus clases llevan IVA, lo explicamos en [el IVA de las clases de pilates](/recursos/iva-clases-de-pilates).' },
          ],
        },
        { t: 'p', texto: 'Cuando tengas la escalera decidida, llevarla a un programa evita errores en recepción. En Tentare configuras [bonos, cuotas mensuales y clases sueltas](/funcionalidades/bonos-y-membresias), con la caducidad de cada bono y reglas distintas por tipo de clase, y tus alumnas reservan y cancelan solas desde el móvil.' },
      ],
    },
    {
      id: 'metodologia',
      titulo: 'Cómo hemos hecho este estudio de precios',
      bloques: [
        {
          t: 'lista',
          items: [
            '**Muestra:** 32 estudios que publican sus tarifas en su web (Madrid 10, Barcelona 8, Valencia 3, Sevilla 3, Bilbao 3, Málaga 2, Zaragoza 2, Alicante 1), consultados el 25 de septiembre de 2026.',
            '**Formatos:** reformer o máquinas en grupo (de 4 a 12 personas), suelo en grupo y privada. Dúos y tríos, fuera de las tablas.',
            '**Fuera:** clases de prueba, packs de bienvenida, promociones, cuotas que mezclan formatos o incluyen otras actividades, y estudios con formato poco claro o precios solo en imagen.',
            '**Precio por sesión:** cuota de N clases a la semana entre 4N; de N clases al mes, entre N; bono, entre sus sesiones.',
            '**Qué no es:** una muestra aleatoria. Solo están los estudios que enseñan sus precios: tómalo como una foto del mercado visible, no como una estadística oficial.',
          ],
        },
        { t: 'p', texto: 'Todos los estudios, con su enlace, están en las fuentes. Las tarifas cambian: compruébalas antes de usarlas en tu plan de negocio.' },
      ],
    },
  ],
  faq: [
    { q: '¿Cuánto cuesta una clase de pilates suelta?', a: 'De mediana, 25 € la de reformer en grupo (de 17 a 35 €), 16 € la de suelo (de 12 a 25 €) y 53,50 € la privada (de 40 a 75 €), según 32 estudios. Con cuota mensual o bono de 10, la sesión de reformer sale alrededor de un 20 % más barata.' },
    { q: '¿Cuánto cuesta el pilates reformer al mes?', a: 'Una clase a la semana, 75 € al mes de mediana (de 60 a 133 €); dos clases, 130 € (de 105 a 200 €). Tres estudios de la muestra venden además tarifa ilimitada, a 185, 195 y 250 € al mes.' },
    { q: '¿Cuánto cuesta una clase particular de pilates?', a: 'Entre 40 y 75 € la sesión suelta (mediana: 53,50 €) y entre 30 y 55 € por sesión con bono de 8 a 10 (mediana: 44,13 €). Suele costar unas dos veces la clase de reformer en grupo del mismo estudio.' },
    { q: '¿Por qué el pilates reformer es más caro que el de suelo?', a: 'Porque el aforo lo marca el número de máquinas y cada una es inversión y mantenimiento; en suelo, otra esterilla cabe casi sin coste. En el mismo estudio, la máquina cuesta entre 1,27 y 2,2 veces el suelo.' },
    { q: '¿Es más barato pagar una cuota mensual que clases sueltas?', a: 'Casi siempre: la cuota de una clase semanal de reformer sale una mediana del 20 % más barata por sesión que la suelta del mismo estudio (entre el 4 % y el 29 %). A cambio, la alumna se compromete un mes.' },
    { q: '¿Cuánto debería cobrar si abro un estudio de pilates?', a: 'Calcula primero tu coste por plaza ocupada y luego compárate con los estudios de tu zona que dan tu formato. Como referencia, la sesión con cuota de una clase semanal está en 18,75 € de mediana en reformer y en 13,75 € en suelo.' },
    { q: '¿Los precios de las clases de pilates llevan IVA?', a: 'A una particular hay que anunciarle el precio total, con todos los impuestos incluidos (artículo 60 de la ley de consumidores). Si tus clases llevan IVA y a qué tipo depende de tu caso: confírmalo con tu gestoría.' },
  ],
  fuentes: [
    { titulo: 'Estudio A Pilates (Madrid): precios', url: 'https://estudioapilates.com/pages/precios', consultada: '2026-09-25' },
    { titulo: 'Siamo Pilates (Madrid): precios', url: 'https://www.siamopilates.com/precios/', consultada: '2026-09-25' },
    { titulo: 'Pinar Pilates (Madrid): precios', url: 'https://pinarpilates.com/precios/', consultada: '2026-09-25' },
    { titulo: 'Pilates Estudio (Madrid): clases y precios', url: 'https://pilatesestudio.es/clases-y-precios/', consultada: '2026-09-25' },
    { titulo: 'Temple Pilates (Madrid): precios', url: 'https://templepilates.es/precios/', consultada: '2026-09-25' },
    { titulo: 'Estación Pilates (Madrid): precios', url: 'https://estacionpilates.es/precios/', consultada: '2026-09-25' },
    { titulo: 'Pilates Evidence Madrid: tarifas', url: 'https://www.pilatesevidence.com/centros/pilates-evidence-madrid/tarifas-pilates-evidence-madrid/', consultada: '2026-09-25' },
    { titulo: 'Olimpia (Madrid): clases y membresías', url: 'https://olimpiatwc.com', consultada: '2026-09-25' },
    { titulo: 'Vit4lid4d (Madrid): tarifas', url: 'https://www.vitalidadpilates.com/tarifas', consultada: '2026-09-25' },
    { titulo: 'Ruth Centro de Pilates (Madrid): tarifas y promociones', url: 'https://ruthpilates.es/tarifas-y-promociones/', consultada: '2026-09-25' },
    { titulo: 'Horta Pilates (Barcelona): precios', url: 'https://www.hortapilates.com/precios/', consultada: '2026-09-25' },
    { titulo: 'Area Pilates (Barcelona): horarios y tarifas', url: 'https://areapilates.com/horarios/', consultada: '2026-09-25' },
    { titulo: 'Beyoga (Barcelona): horarios y precios', url: 'https://beyogabcn.com/horarios-y-precios-clases-yoga-pilates-hipopresivos-en-barcelona/', consultada: '2026-09-25' },
    { titulo: 'Original Pilates Barcelona: pilates reformer en el Eixample', url: 'https://www.originalpilatesbcn.com/pilates-reformer-en-el-eixample/', consultada: '2026-09-25' },
    { titulo: 'FAB Pilates (Barcelona): pilates reformer', url: 'https://fab-pilates.com/pilates-reformer-barcelona', consultada: '2026-09-25' },
    { titulo: 'NEXES BCN Gràcia (Barcelona): cuotas', url: 'https://nexespilates.com/cuotas-de-nexes-bcn-gracia/', consultada: '2026-09-25' },
    { titulo: 'PILAT3S Gràcia (Barcelona): estudio y precios', url: 'https://pilat3s.com/studio/pilat3s-gracia/', consultada: '2026-09-25' },
    { titulo: 'Pilates10 Barcelona Gràcia: tarifas', url: 'https://www.pilates10.com/barcelona/gracia/es_ES/', consultada: '2026-09-25' },
    { titulo: 'Raquel Boti Pilates Estudio (Valencia): tarifas', url: 'https://raquelbotipilatesestudio.com/tarifas/', consultada: '2026-09-25' },
    { titulo: 'Pilates Training Studio (Valencia): tarifas', url: 'https://www.pilatestrainingstudio.com/tarifas/', consultada: '2026-09-25' },
    { titulo: 'Rona Pilates Reformer (Valencia): precios', url: 'https://www.ronapilates.com/', consultada: '2026-09-25' },
    { titulo: 'Corestudio (Sevilla): tarifas', url: 'https://corestudiopilates.es/tarifas/', consultada: '2026-09-25' },
    { titulo: 'Motio Pilates (Sevilla): tarifas', url: 'https://motiopilates.es/clases/', consultada: '2026-09-25' },
    { titulo: 'Pilates Salud (Sevilla): precios', url: 'https://pilatessaludsevilla.com/precio', consultada: '2026-09-25' },
    { titulo: 'Balanza Pilates (Bilbao): precio de las clases', url: 'https://balanzapilates.com/precio-clases-de-pilates-en-bilbao/', consultada: '2026-09-25' },
    { titulo: 'Club Pilates Indautxu (Bilbao): suscripciones', url: 'https://clubpilatesindautxu.es/', consultada: '2026-09-25' },
    { titulo: 'Kinesshia Pilates (Bilbao): tarifas', url: 'https://www.kinesshia.com/inicio/bienvenidos-a-kinesshia/tarifas', consultada: '2026-09-25' },
    { titulo: 'Estudio Pilates Málaga: tarifas', url: 'https://estudiopilatesmalaga.com/tarifas/', consultada: '2026-09-25' },
    { titulo: 'MR Pilates (Málaga): precios', url: 'https://mrpilates.es/precios/', consultada: '2026-09-25' },
    { titulo: 'Tout Suite (Zaragoza): pilates reformer', url: 'https://toutsuite.es/fitness/pilates-maquina-zaragoza/', consultada: '2026-09-25' },
    { titulo: 'True Pilates Zaragoza: clases y tarifas', url: 'https://truepilateszaragoza.com/clases-y-tarifas/', consultada: '2026-09-25' },
    { titulo: 'BYBO Studios (Alicante): pilates reformer', url: 'https://www.bybostudios.com/reservar-pilates-reformer', consultada: '2026-09-25' },
    { titulo: 'BOE: Real Decreto Legislativo 1/2007, texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios (art. 60)', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-20555', consultada: '2026-09-25' },
  ],
  relacionadas: [
    '/recursos/precios-reformer-mat',
    '/recursos/bonos-de-pilates',
    '/recursos/rentabilidad-estudio-de-pilates',
    '/funcionalidades/bonos-y-membresias',
  ],
  cta: {
    titulo: 'Bonos, cuotas y clases sueltas en un mismo sitio',
    texto: 'En Tentare configuras bonos, cuotas mensuales y clases sueltas con su caducidad y reglas por tipo de clase, y tus alumnas reservan y cancelan solas desde el móvil. Prueba 7 días gratis, sin tarjeta, el plan que elijas.',
  },
  revision: [
    'Muestra no aleatoria: solo estudios que publican precios en su web. Las tarifas cambian; revisar las cifras antes de cada actualización del artículo.',
    'PILAT3S Gràcia enseña sus cuotas con precio tachado (45 € frente a 90 €) sin decir si es solo el primer mes: se excluyeron sus cuotas y solo cuentan su clase suelta (30 €) y su bono de 10 (200 €).',
    'Olimpia publica «Single Reformer Class: 30€» y, en otro bloque, un «drop-in» de reformer a 25 €: se tomó 30 €.',
    'Pilates Evidence Madrid publica «4 SESIONES 60 € (Consumir en 1 mes)» junto a su clase de grupo a 25 €, sin aclarar si es una oferta de iniciación: fuera de la muestra. Beyoga: su tarifa de reformer (119 €, 4 clases) incluye clases ilimitadas de otras actividades: fuera de la cuota de reformer.',
    'Fuera por formato o número de sesiones poco claros: grupos de Estudio A Pilates (solo cuentan sus privadas), grupos de Kinesshia (solo cuentan sus privadas), Belle Pilates y Melic (Valencia), Body Mechanics (Barcelona), Estudio Training (Bilbao) y Pilates10 Sevilla Los Remedios (cuotas combinadas).',
    'Estudio Pilates Málaga (máximo 4 personas) y Pilates Salud (Sevilla, sin número) venden las máquinas como «semiprivada»: se contaron como máquinas en grupo.',
    'Club Pilates Indautxu: un resultado de búsqueda daba 80/140/180 €; su web del 25-sep dice 92/150/185 €. Se usó la web. Tout Suite: un resultado de búsqueda citaba «precios a febrero de 2023», nota que no aparece en su página actual; su tienda confirma 21 € la sesión suelta, IVA incluido.',
    'Siamo Pilates vende las privadas como «Bono 4/8 sesiones» a 160/290 €/mes: se trataron como cuota mensual de 4 y 8 sesiones.',
  ],
};

export default articulo;
